### ISSUE TITLE
panic due to spf check

### ISSUE THREAD

**Issue by erebe** [viridIT/vSMTP#1026]
**Describe the bug**

Vsmtp is panicking with 
```
panicked at 'called `Result::unwrap()` on an `Err` value: BadState', src/vsmtp/vsmtp-rule-engine/src/api/spf.rs:327:10                                                                                                                                                                      
 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This only happens when I add the spf rule (either at rcpt or mail stage)
```
        rule "check spf" || spf::check("both", "soft"),
```

Also, the documentation at https://vsmtp.rs/ref/vSL/api/fn::global::spf.html#effective-smtp-stage is misleading because the effective stage mentioned is "rcpt" but the example below is using the mail stage which is before rcpt

**To Reproduce**
`config.vsl`
```
fn on_config(config) {

  // Change the name of the server.
  config.server.name = "mail.erebe.eu";

  // Specify addresses that the server will listen to.
  config.server.interfaces = #{
    addr: ["[::]:25"],
    addr_submission: ["[::]:587"],
    addr_submissions: ["[::]:465"],
  };

  config.server.tls = #{
    preempt_cipherlist: false,
    handshake_timeout: "1000ms",
    protocol_version: ["TLSv1.2", "TLSv1.3"],
  };

  config.server.logs = #{
      "level": [ "trace" ],
  };

  config.server.virtual = #{
    "mail.erebe.eu": #{
      "is_default": true,
      "tls": #{
          protocol_version: ["TLSv1.2", "TLSv1.3"],
          certificate: "/etc/dovecot/private/tls.crt",
          private_key: "/etc/dovecot/private/tls.key",
      }
    },
    "erebe.eu": #{
      "tls": #{
          protocol_version: ["TLSv1.2", "TLSv1.3"],
          certificate: "/etc/dovecot/private/tls.crt",
          private_key: "/etc/dovecot/private/tls.key",
      }
    }
  };

  // Change filter rules locations.
  config.app.vsl.filter_path = "/etc/vsmtp/filter.vsl";
  //config.app.vsl.domain_dir = "/etc/vsmtp/domain-enabled";

  config.server.system = #{
      "thread_pool": #{
          "delivery": 1,
          "processing": 1,
          "receiver": 1,
      }
  };

  return config;
}
```

`filter.vsl`
```
    mail: [
      // After MAIL FROM command
      rule "deny unencrypted" || {
        log("warn", `Email from ${ctx::client_ip()}`);
        if ctx::is_secured() || ctx::client_ip() == "::1" || ctx::client_ip() == "127.0.0.1" {
          state::next()
        } else {
          state::deny(code(451, "5.7.3", "Must issue a STARTTLS command first\r\n"))
        }
      }
    ],

    rcpt: [
        // After each RCPT TO command
        rule "verify for host" || {
                if "erebe.eu" in ctx::rcpt_list().domains {
                        state::next()
                } else {
                        log("warn", `Refusing email for ${ctx::rcpt_list()}`);
                        state::deny()
                }
        },
        
        // HERE HERE HERE HERE
        rule "check spf" || spf::check("both", "soft"),
        // HERE HERE HERE HERE
    ],

    preq: [
        rule "write mail to disk" || {
              fs::write("/data/mail-tmp");
              // we deny to avoid queuing but tell client everything is ok
              state::deny(code(250, "Ok\r\n"))
        }
    ],
```

**Expected behavior**
Vsmtp should not crash and correctly receive the email

**Screenshots**
```
2023-02-20T10:07:54.568933Z  INFO serve:handle-client: Connection accepted. kind=Relay client=[2607:f8b0:4864:20::1035]:44872 server=:25
2023-02-20T10:07:54.571911Z  INFO run_session:rule: return=Next uuid=a7c874b6-ca88-4449-9d8b-f3ca0a3bb2b6 stage=connect
2023-02-20T10:07:54.710215Z  INFO run_session:rule: return=Next uuid=a7c874b6-ca88-4449-9d8b-f3ca0a3bb2b6 stage=helo
2023-02-20T10:07:55.146427Z  INFO run_session:rule: return=Next uuid=a7c874b6-ca88-4449-9d8b-f3ca0a3bb2b6 stage=helo
2023-02-20T10:07:55.422297Z  WARN run_session:rule:execute: Email from 2607:f8b0:4864:20::1035 uuid=a7c874b6-ca88-4449-9d8b-f3ca0a3bb2b6 stage=mail self=rule { name: "deny unencrypted", .. }
2023-02-20T10:07:55.424707Z  INFO run_session:rule:execute: return=Next uuid=a7c874b6-ca88-4449-9d8b-f3ca0a3bb2b6 stage=mail self=rule { name: "deny unencrypted", .. }
2023-02-20T10:07:55.424812Z  INFO run_session:rule: return=Next uuid=a7c874b6-ca88-4449-9d8b-f3ca0a3bb2b6 stage=mail
2023-02-20T10:07:55.565001Z  INFO run_session:rule:execute: return=Next uuid=a7c874b6-ca88-4449-9d8b-f3ca0a3bb2b6 stage=rcpt self=rule { name: "verify for host", .. }
thread 'receiver-child' panicked at 'called `Result::unwrap()` on an `Err` value: BadState', src/vsmtp/vsmtp-rule-engine/src/api/spf.rs:327:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**System (please complete the following information):**
- vSMTP version: v2.1.1
- OS: debian
- OS version: bullseye

**Additional context**

**Comment by ltabis** [comment]
Thank you @erebe, I'll make sure that the doc is clear and that the function returns an error instead of panicking when the wrong stage is used.

**Comment by ltabis** [comment]
As a quick fix you can move your spf code to the preq stage while I'm working on this. Tell me if it works out for you !

**Comment by erebe** [comment]
Hello @ltabis ,

Indeed at preq stage, it works :+1:

**Comment by ltabis** [comment]
> Indeed at preq stage, it works

Awesome. I'm working on a PR to make `spf::check` available from the `mail` stage, i'll keep you posted.

**Comment by ltabis** [comment]
It has been fixed in https://github.com/viridIT/vSMTP/pull/1027, thank you for the report !
